### ISSUE TITLE
HA 0.97.0 killed the display

### ISSUE THREAD

**Issue by rocksolid2018** [daemondazz/homeassistant-displays#15]
upgraded to HA 0.97.0 and fire kiosk display component stops working. 

Invalid config for [display]: [name] is an invalid option for [display]. Check: display->name. (See /config/configuration.yaml, line 659). Please check the docs at https://home-assistant.io/components/display/

**Comment by daemondazz** [comment]
Thanks for your report. I just updated my install to 0.97.2 and am unable to reproduce the error. 

Are you running the latest code from GitHub as this looks like the issue that was fixed in #12?

**Comment by rocksolid2018** [comment]
it works after updating the code, thanks @daemondazz
