### ISSUE TITLE
HA 0.104 breaks displays integration

### ISSUE THREAD

**Issue by syphernl** [daemondazz/homeassistant-displays#17]
When starting up it shows the following:
```
Jan 16 09:54:32 hass hass[37637]: 2020-01-16 09:54:32 ERROR (MainThread) [homeassistant.setup] Error during setup of component display
Jan 16 09:54:32 hass hass[37637]: Traceback (most recent call last):
Jan 16 09:54:32 hass hass[37637]:   File "/srv/hass/lib/python3.8/site-packages/homeassistant/setup.py", line 169, in _async_setup_component
Jan 16 09:54:32 hass hass[37637]:     result = await component.async_setup(  # type: ignore
Jan 16 09:54:32 hass hass[37637]:   File "/home/hass/.homeassistant/custom_components/display/__init__.py", line 72, in async_setup
Jan 16 09:54:32 hass hass[37637]:     component = EntityComponent(
Jan 16 09:54:32 hass hass[37637]: TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given
```

**Comment by ercsey** [comment]
Same problem here.

**Comment by yoni3210** [comment]
Same Problem Here:
2020-01-16 16:40:55 ERROR (MainThread) [homeassistant.setup] Error during setup of component display
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/display/__init__.py", line 73, in async_setup
    _LOGGER, DOMAIN, hass, SCAN_INTERVAL, GROUP_NAME_ALL_DISPLAYS)
TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given

**Comment by daemondazz** [comment]
Thanks for reporting this issue. I've just pushed a change which should only try to load the group.all_displays entity on HA < 0.104

**Comment by syphernl** [comment]
Thanks for the quick fix, it works again! 👍
