### ISSUE TITLE
Add feature: motion detection (already supported by the Fully Kiosk Rest API)

### ISSUE THREAD

**Issue by recklessnl** [daemondazz/homeassistant-displays#20]
The Fully Kiosk Rest API already shows whether or not motion has been detected. If I login and do remote admin via port 2323, I can see whether or not motion has been detected.

Therefore it should be fairly easy to have this component support motion detection from the kiosk tablet as well. I would love to have this feature.

The same goes for acoustic and movement features as seen on the remote admin page:

![image](https://user-images.githubusercontent.com/41142401/75082990-f8fb2100-54db-11ea-831f-69e1fd3905c7.png)

**Comment by Madseason41** [comment]
Can't you use see this with MQTT enabled on Fully and a MQTT sensor on HA?

**Comment by Madseason41** [comment]
> Can't you use see this with MQTT enabled on Fully and a MQTT sensor on HA?

Never mind, I actually think adding the rest api or mqtt data to this component would be better. It would be nice if it created a binary sensor for motion like the browser_mode component. Unfortunately that one requires the use of Lovelace and I use appdaemon. It works well with this component.

**Comment by GuruPG** [comment]
Yes please. Would be great to add this.

**Comment by daemondazz** [comment]
I'm not sure how useful this would be via the Rest API as it's polling based not pushed based. Getting Fully to push an alert directly via MQTT would be much more responsive.
