### ISSUE TITLE
Can't figure it out

### ISSUE THREAD

**Issue by gdslone** [daemondazz/homeassistant-displays#21]
So i was able to get to the services and install custom components. I Assigned my device via the config.yaml. I am unable to get my android devices to respond to the call services. How in android do you enable remote management? (I tried google rather unsuccesfully)

**Comment by gdslone** [comment]
Figured it out, sorry.

**Comment by sgillespie** [comment]
For anyone looking for this, it is a setting in Fully Kiosk (PLUS)
