### ISSUE TITLE
same as #24

### ISSUE THREAD

**Issue by GuruPG** [daemondazz/homeassistant-displays#25]
Sorry, looks like its still an issue.

I have deleted my 'display' and 'fully_kiosk' folders from HA and replaced with the latest ones you have just updated but I'm having the same issue.
works fine on core 2021.5.5 but as soon as i update to 2021.6.1 it gives me the  Integration 'display' not found error.

**Comment by daemondazz** [comment]
I've re-opened #24 for you.
